#!/bin/bash
#compile tex files , bib (if mod) and clean aux files


# init stat shell vars
eval $(stat -s $1.bib)
mTime=$st_mtime
# compile bibliography
function bib(){
		biber "$1"
		pdflatex "$1.tex"
		pdflatex "$1.tex"
	}

if [[ ! (-e ".tmp.sh") ]] ; then
	echo "preTime=$mTime" > ".tmp.sh"
	pdflatex "$1.tex"
	bib $1
else
	source .tmp.sh
	if [[ preTime -eq mTime ]] ; then
		pdflatex "$1.tex"
	else
		pdflatex "$1.tex"
		bib $1
	fi
fi

#clear aux files
latexmk -c
rm *\.xml
